version: '3'
services:
  app1:
    build:
      context: ./web1
      dockerfile: Dockerfile
    ports:
      - "4000:3000"

  app2:
    build:
      context: ./web2
      dockerfile: Dockerfile
    ports:
      - "4001:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
