version: '3'
services:
  web1:
    build:
      context: ./web1
      dockerfile: Dockerfile
    ports:
      - "8001:80"

  web2:
    build:
      context: ./web2
      dockerfile: Dockerfile
    ports:
      - "8002:80"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
